/*
 * FRAMMap.h
 *
 *  Created on: June 65, 2020
 *      Author: Zhuoheng
 *
 */

#ifndef OBCFRAMMAP_H_
#define OBCFRAMMAP_H_

#include "FRAMMap.h"

// TODO: dynamic FRAM management (save size in fram)
#define ADBTELEMETRY_FRAM_OFFSET            5000
#define ADBTELEMETRY_FRAM_SIZE              26

#define ADCSTELEMETRY_FRAM_OFFSET           ADBTELEMETRY_FRAM_OFFSET + ADBTELEMETRY_FRAM_SIZE
#define ADCSTELEMETRY_FRAM_SIZE             26

#define COMMSTELEMETRY_FRAM_OFFSET          ADCSTELEMETRY_FRAM_OFFSET + ADCSTELEMETRY_FRAM_SIZE
#define COMMSTELEMETRY_FRAM_SIZE            66

#define EPSTELEMETRY_FRAM_OFFSET            COMMSTELEMETRY_FRAM_OFFSET + COMMSTELEMETRY_FRAM_SIZE
#define EPSTELEMETRY_FRAM_SIZE              87

#define PROPTELEMETRY_FRAM_OFFSET           EPSTELEMETRY_FRAM_OFFSET + EPSTELEMETRY_FRAM_SIZE
#define PROPTELEMETRY_FRAM_SIZE             26

#define OBCVARIABLE_FRAM_OFFSET             PROPTELEMETRY_FRAM_OFFSET + PROPTELEMETRY_FRAM_SIZE
#define OBCVARIABLE_FRAM_SIZE               63

#endif /* OBCFRAMMAP_H_ */
