//File Generated By TelemetryFromXTCE.py

#ifndef OBCTELEMETRYCONTAINER_H_
#define OBCTELEMETRYCONTAINER_H_

#include "TelemetryContainer.h"

#define OBC_CONTAINER_SIZE  23

class OBCTelemetryContainer : public TelemetryContainer
{
protected:
unsigned char telemetry[OBC_CONTAINER_SIZE];

public:
    virtual int size();
    virtual unsigned char * getArray();

    char getStatus();
    void setStatus(char var);

    char getBootCounter();
    void setBootCounter(char var);

    long getResetCause();
    void setResetCause(long var);

    unsigned long getUptime();
    void setUptime(unsigned long var);

    unsigned long getTotalUptime();
    void setTotalUptime(unsigned long var);

    char getVersionNumber();
    void setVersionNumber(char var);

    short getMCUTemp();
    void setMCUTemp(short var);

    bool getINAStatus();
    void setINAStatus(bool var);

    bool getTMPStatus();
    void setTMPStatus(bool var);

    short getVoltage();
    void setVoltage(short var);

    short getCurrent();
    void setCurrent(short var);

    short getTemperature();
    void setTemperature(short var);

};

#endif /* OBCTELEMETRYCONTAINER_H_ */
