//File Generated By TelemetryFromXTCE.py

#include "EPSTelemetryContainer.h"

int EPSTelemetryContainer::size()
{
    return EPS_CONTAINER_SIZE;
}

unsigned char* EPSTelemetryContainer::getArray()
{
    return &telemetry[0];
}

char EPSTelemetryContainer::getStatus()
{
    return telemetry[0];
}
void EPSTelemetryContainer::setStatus(char uchar)
{
    telemetry[0] = uchar;
}
char EPSTelemetryContainer::getBootCounter()
{
    return telemetry[1];
}
void EPSTelemetryContainer::setBootCounter(char uchar)
{
    telemetry[1] = uchar;
}
long EPSTelemetryContainer::getResetCause()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[2] = telemetry[2];
    ((unsigned char *)&ulong)[1] = telemetry[3];
    ((unsigned char *)&ulong)[0] = telemetry[4];
    return ulong;
}
void EPSTelemetryContainer::setResetCause(long ulong)
{
    telemetry[2] = ((unsigned char *)&ulong)[2];
    telemetry[3] = ((unsigned char *)&ulong)[1];
    telemetry[4] = ((unsigned char *)&ulong)[0];
}
unsigned long EPSTelemetryContainer::getUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[5];
    ((unsigned char *)&ulong)[2] = telemetry[6];
    ((unsigned char *)&ulong)[1] = telemetry[7];
    ((unsigned char *)&ulong)[0] = telemetry[8];
    return ulong;
}
void EPSTelemetryContainer::setUptime(unsigned long ulong)
{
    telemetry[5] = ((unsigned char *)&ulong)[3];
    telemetry[6] = ((unsigned char *)&ulong)[2];
    telemetry[7] = ((unsigned char *)&ulong)[1];
    telemetry[8] = ((unsigned char *)&ulong)[0];
}
unsigned long EPSTelemetryContainer::getTotalUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[9];
    ((unsigned char *)&ulong)[2] = telemetry[10];
    ((unsigned char *)&ulong)[1] = telemetry[11];
    ((unsigned char *)&ulong)[0] = telemetry[12];
    return ulong;
}
void EPSTelemetryContainer::setTotalUptime(unsigned long ulong)
{
    telemetry[9] = ((unsigned char *)&ulong)[3];
    telemetry[10] = ((unsigned char *)&ulong)[2];
    telemetry[11] = ((unsigned char *)&ulong)[1];
    telemetry[12] = ((unsigned char *)&ulong)[0];
}
char EPSTelemetryContainer::getVersionNumber()
{
    return telemetry[13];
}
void EPSTelemetryContainer::setVersionNumber(char uchar)
{
    telemetry[13] = uchar;
}
short EPSTelemetryContainer::getMCUTemp()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[14];
    ((unsigned char *)&ushort)[0] = telemetry[15];
    return ushort;
}
void EPSTelemetryContainer::setMCUTemp(short ushort)
{
    telemetry[14] = ((unsigned char *)&ushort)[1];
    telemetry[15] = ((unsigned char *)&ushort)[0];
}
bool EPSTelemetryContainer::getBatteryINAStatus()
{
    return ((telemetry[16] & 0x80) != 0);
}
void EPSTelemetryContainer::setBatteryINAStatus(bool bval)
{
    telemetry[16] &= (~0x80);
    telemetry[16] |= bval ? 0x80 : 0x00;
}
bool EPSTelemetryContainer::getBatteryGGStatus()
{
    return ((telemetry[16] & 0x40) != 0);
}
void EPSTelemetryContainer::setBatteryGGStatus(bool bval)
{
    telemetry[16] &= (~0x40);
    telemetry[16] |= bval ? 0x40 : 0x00;
}
bool EPSTelemetryContainer::getInternalINAStatus()
{
    return ((telemetry[16] & 0x20) != 0);
}
void EPSTelemetryContainer::setInternalINAStatus(bool bval)
{
    telemetry[16] &= (~0x20);
    telemetry[16] |= bval ? 0x20 : 0x00;
}
bool EPSTelemetryContainer::getUnregulatedINAStatus()
{
    return ((telemetry[16] & 0x10) != 0);
}
void EPSTelemetryContainer::setUnregulatedINAStatus(bool bval)
{
    telemetry[16] &= (~0x10);
    telemetry[16] |= bval ? 0x10 : 0x00;
}
bool EPSTelemetryContainer::getBus1INAStatus()
{
    return ((telemetry[16] & 0x08) != 0);
}
void EPSTelemetryContainer::setBus1INAStatus(bool bval)
{
    telemetry[16] &= (~0x08);
    telemetry[16] |= bval ? 0x08 : 0x00;
}
bool EPSTelemetryContainer::getBus2INAStatus()
{
    return ((telemetry[16] & 0x04) != 0);
}
void EPSTelemetryContainer::setBus2INAStatus(bool bval)
{
    telemetry[16] &= (~0x04);
    telemetry[16] |= bval ? 0x04 : 0x00;
}
bool EPSTelemetryContainer::getBus3INAStatus()
{
    return ((telemetry[16] & 0x02) != 0);
}
void EPSTelemetryContainer::setBus3INAStatus(bool bval)
{
    telemetry[16] &= (~0x02);
    telemetry[16] |= bval ? 0x02 : 0x00;
}
bool EPSTelemetryContainer::getBus4INAStatus()
{
    return ((telemetry[16] & 0x01) != 0);
}
void EPSTelemetryContainer::setBus4INAStatus(bool bval)
{
    telemetry[16] &= (~0x01);
    telemetry[16] |= bval ? 0x01 : 0x00;
}
bool EPSTelemetryContainer::getBus4Error()
{
    return ((telemetry[17] & 0x80) != 0);
}
void EPSTelemetryContainer::setBus4Error(bool bval)
{
    telemetry[17] &= (~0x80);
    telemetry[17] |= bval ? 0x80 : 0x00;
}
bool EPSTelemetryContainer::getBus3Error()
{
    return ((telemetry[17] & 0x40) != 0);
}
void EPSTelemetryContainer::setBus3Error(bool bval)
{
    telemetry[17] &= (~0x40);
    telemetry[17] |= bval ? 0x40 : 0x00;
}
bool EPSTelemetryContainer::getBus2Error()
{
    return ((telemetry[17] & 0x20) != 0);
}
void EPSTelemetryContainer::setBus2Error(bool bval)
{
    telemetry[17] &= (~0x20);
    telemetry[17] |= bval ? 0x20 : 0x00;
}
bool EPSTelemetryContainer::getBus1Error()
{
    return ((telemetry[17] & 0x10) != 0);
}
void EPSTelemetryContainer::setBus1Error(bool bval)
{
    telemetry[17] &= (~0x10);
    telemetry[17] |= bval ? 0x10 : 0x00;
}
bool EPSTelemetryContainer::getBus4State()
{
    return ((telemetry[17] & 0x08) != 0);
}
void EPSTelemetryContainer::setBus4State(bool bval)
{
    telemetry[17] &= (~0x08);
    telemetry[17] |= bval ? 0x08 : 0x00;
}
bool EPSTelemetryContainer::getBus3State()
{
    return ((telemetry[17] & 0x04) != 0);
}
void EPSTelemetryContainer::setBus3State(bool bval)
{
    telemetry[17] &= (~0x04);
    telemetry[17] |= bval ? 0x04 : 0x00;
}
bool EPSTelemetryContainer::getBus2State()
{
    return ((telemetry[17] & 0x02) != 0);
}
void EPSTelemetryContainer::setBus2State(bool bval)
{
    telemetry[17] &= (~0x02);
    telemetry[17] |= bval ? 0x02 : 0x00;
}
bool EPSTelemetryContainer::getBus1State()
{
    return ((telemetry[17] & 0x01) != 0);
}
void EPSTelemetryContainer::setBus1State(bool bval)
{
    telemetry[17] &= (~0x01);
    telemetry[17] |= bval ? 0x01 : 0x00;
}
bool EPSTelemetryContainer::getPanelYpINAStatus()
{
    return ((telemetry[18] & 0x80) != 0);
}
void EPSTelemetryContainer::setPanelYpINAStatus(bool bval)
{
    telemetry[18] &= (~0x80);
    telemetry[18] |= bval ? 0x80 : 0x00;
}
bool EPSTelemetryContainer::getPanelYmINAStatus()
{
    return ((telemetry[18] & 0x40) != 0);
}
void EPSTelemetryContainer::setPanelYmINAStatus(bool bval)
{
    telemetry[18] &= (~0x40);
    telemetry[18] |= bval ? 0x40 : 0x00;
}
bool EPSTelemetryContainer::getPanelXpINAStatus()
{
    return ((telemetry[18] & 0x20) != 0);
}
void EPSTelemetryContainer::setPanelXpINAStatus(bool bval)
{
    telemetry[18] &= (~0x20);
    telemetry[18] |= bval ? 0x20 : 0x00;
}
bool EPSTelemetryContainer::getPanelXmINAStatus()
{
    return ((telemetry[18] & 0x10) != 0);
}
void EPSTelemetryContainer::setPanelXmINAStatus(bool bval)
{
    telemetry[18] &= (~0x10);
    telemetry[18] |= bval ? 0x10 : 0x00;
}
bool EPSTelemetryContainer::getPanelYpTMPStatus()
{
    return ((telemetry[18] & 0x08) != 0);
}
void EPSTelemetryContainer::setPanelYpTMPStatus(bool bval)
{
    telemetry[18] &= (~0x08);
    telemetry[18] |= bval ? 0x08 : 0x00;
}
bool EPSTelemetryContainer::getPanelYmTMPStatus()
{
    return ((telemetry[18] & 0x04) != 0);
}
void EPSTelemetryContainer::setPanelYmTMPStatus(bool bval)
{
    telemetry[18] &= (~0x04);
    telemetry[18] |= bval ? 0x04 : 0x00;
}
bool EPSTelemetryContainer::getPanelXpTMPStatus()
{
    return ((telemetry[18] & 0x02) != 0);
}
void EPSTelemetryContainer::setPanelXpTMPStatus(bool bval)
{
    telemetry[18] &= (~0x02);
    telemetry[18] |= bval ? 0x02 : 0x00;
}
bool EPSTelemetryContainer::getPanelXmTMPStatus()
{
    return ((telemetry[18] & 0x01) != 0);
}
void EPSTelemetryContainer::setPanelXmTMPStatus(bool bval)
{
    telemetry[18] &= (~0x01);
    telemetry[18] |= bval ? 0x01 : 0x00;
}
bool EPSTelemetryContainer::getMpptYpINAStatus()
{
    return ((telemetry[19] & 0x80) != 0);
}
void EPSTelemetryContainer::setMpptYpINAStatus(bool bval)
{
    telemetry[19] &= (~0x80);
    telemetry[19] |= bval ? 0x80 : 0x00;
}
bool EPSTelemetryContainer::getMpptYmINAStatus()
{
    return ((telemetry[19] & 0x40) != 0);
}
void EPSTelemetryContainer::setMpptYmINAStatus(bool bval)
{
    telemetry[19] &= (~0x40);
    telemetry[19] |= bval ? 0x40 : 0x00;
}
bool EPSTelemetryContainer::getMpptXpINAStatus()
{
    return ((telemetry[19] & 0x20) != 0);
}
void EPSTelemetryContainer::setMpptXpINAStatus(bool bval)
{
    telemetry[19] &= (~0x20);
    telemetry[19] |= bval ? 0x20 : 0x00;
}
bool EPSTelemetryContainer::getMpptXmINAStatus()
{
    return ((telemetry[19] & 0x10) != 0);
}
void EPSTelemetryContainer::setMpptXmINAStatus(bool bval)
{
    telemetry[19] &= (~0x10);
    telemetry[19] |= bval ? 0x10 : 0x00;
}
bool EPSTelemetryContainer::getCellYpINAStatus()
{
    return ((telemetry[19] & 0x08) != 0);
}
void EPSTelemetryContainer::setCellYpINAStatus(bool bval)
{
    telemetry[19] &= (~0x08);
    telemetry[19] |= bval ? 0x08 : 0x00;
}
bool EPSTelemetryContainer::getCellYmINAStatus()
{
    return ((telemetry[19] & 0x04) != 0);
}
void EPSTelemetryContainer::setCellYmINAStatus(bool bval)
{
    telemetry[19] &= (~0x04);
    telemetry[19] |= bval ? 0x04 : 0x00;
}
bool EPSTelemetryContainer::getCellXpINAStatus()
{
    return ((telemetry[19] & 0x02) != 0);
}
void EPSTelemetryContainer::setCellXpINAStatus(bool bval)
{
    telemetry[19] &= (~0x02);
    telemetry[19] |= bval ? 0x02 : 0x00;
}
bool EPSTelemetryContainer::getCellXmINAStatus()
{
    return ((telemetry[19] & 0x01) != 0);
}
void EPSTelemetryContainer::setCellXmINAStatus(bool bval)
{
    telemetry[19] &= (~0x01);
    telemetry[19] |= bval ? 0x01 : 0x00;
}
short EPSTelemetryContainer::getInternalINACurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[20];
    ((unsigned char *)&ushort)[0] = telemetry[21];
    return ushort;
}
void EPSTelemetryContainer::setInternalINACurrent(short ushort)
{
    telemetry[20] = ((unsigned char *)&ushort)[1];
    telemetry[21] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getInternalINAVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[22];
    ((unsigned char *)&ushort)[0] = telemetry[23];
    return ushort;
}
void EPSTelemetryContainer::setInternalINAVoltage(short ushort)
{
    telemetry[22] = ((unsigned char *)&ushort)[1];
    telemetry[23] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getUnregulatedINACurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[24];
    ((unsigned char *)&ushort)[0] = telemetry[25];
    return ushort;
}
void EPSTelemetryContainer::setUnregulatedINACurrent(short ushort)
{
    telemetry[24] = ((unsigned char *)&ushort)[1];
    telemetry[25] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getUnregulatedINAVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[26];
    ((unsigned char *)&ushort)[0] = telemetry[27];
    return ushort;
}
void EPSTelemetryContainer::setUnregulatedINAVoltage(short ushort)
{
    telemetry[26] = ((unsigned char *)&ushort)[1];
    telemetry[27] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryGGVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[28];
    ((unsigned char *)&ushort)[0] = telemetry[29];
    return ushort;
}
void EPSTelemetryContainer::setBatteryGGVoltage(short ushort)
{
    telemetry[28] = ((unsigned char *)&ushort)[1];
    telemetry[29] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryINAVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[30];
    ((unsigned char *)&ushort)[0] = telemetry[31];
    return ushort;
}
void EPSTelemetryContainer::setBatteryINAVoltage(short ushort)
{
    telemetry[30] = ((unsigned char *)&ushort)[1];
    telemetry[31] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryINACurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[32];
    ((unsigned char *)&ushort)[0] = telemetry[33];
    return ushort;
}
void EPSTelemetryContainer::setBatteryINACurrent(short ushort)
{
    telemetry[32] = ((unsigned char *)&ushort)[1];
    telemetry[33] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryGGCapacity()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[34];
    ((unsigned char *)&ushort)[0] = telemetry[35];
    return ushort;
}
void EPSTelemetryContainer::setBatteryGGCapacity(short ushort)
{
    telemetry[34] = ((unsigned char *)&ushort)[1];
    telemetry[35] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryGGTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[36];
    ((unsigned char *)&ushort)[0] = telemetry[37];
    return ushort;
}
void EPSTelemetryContainer::setBatteryGGTemperature(short ushort)
{
    telemetry[36] = ((unsigned char *)&ushort)[1];
    telemetry[37] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBatteryTMP20Temperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[38];
    ((unsigned char *)&ushort)[0] = telemetry[39];
    return ushort;
}
void EPSTelemetryContainer::setBatteryTMP20Temperature(short ushort)
{
    telemetry[38] = ((unsigned char *)&ushort)[1];
    telemetry[39] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus4Current()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[40];
    ((unsigned char *)&ushort)[0] = telemetry[41];
    return ushort;
}
void EPSTelemetryContainer::setBus4Current(short ushort)
{
    telemetry[40] = ((unsigned char *)&ushort)[1];
    telemetry[41] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus3Current()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[42];
    ((unsigned char *)&ushort)[0] = telemetry[43];
    return ushort;
}
void EPSTelemetryContainer::setBus3Current(short ushort)
{
    telemetry[42] = ((unsigned char *)&ushort)[1];
    telemetry[43] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus2Current()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[44];
    ((unsigned char *)&ushort)[0] = telemetry[45];
    return ushort;
}
void EPSTelemetryContainer::setBus2Current(short ushort)
{
    telemetry[44] = ((unsigned char *)&ushort)[1];
    telemetry[45] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus1Current()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[46];
    ((unsigned char *)&ushort)[0] = telemetry[47];
    return ushort;
}
void EPSTelemetryContainer::setBus1Current(short ushort)
{
    telemetry[46] = ((unsigned char *)&ushort)[1];
    telemetry[47] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus4Voltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[48];
    ((unsigned char *)&ushort)[0] = telemetry[49];
    return ushort;
}
void EPSTelemetryContainer::setBus4Voltage(short ushort)
{
    telemetry[48] = ((unsigned char *)&ushort)[1];
    telemetry[49] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus3Voltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[50];
    ((unsigned char *)&ushort)[0] = telemetry[51];
    return ushort;
}
void EPSTelemetryContainer::setBus3Voltage(short ushort)
{
    telemetry[50] = ((unsigned char *)&ushort)[1];
    telemetry[51] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus2Voltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[52];
    ((unsigned char *)&ushort)[0] = telemetry[53];
    return ushort;
}
void EPSTelemetryContainer::setBus2Voltage(short ushort)
{
    telemetry[52] = ((unsigned char *)&ushort)[1];
    telemetry[53] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getBus1Voltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[54];
    ((unsigned char *)&ushort)[0] = telemetry[55];
    return ushort;
}
void EPSTelemetryContainer::setBus1Voltage(short ushort)
{
    telemetry[54] = ((unsigned char *)&ushort)[1];
    telemetry[55] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[56];
    ((unsigned char *)&ushort)[0] = telemetry[57];
    return ushort;
}
void EPSTelemetryContainer::setPanelYpCurrent(short ushort)
{
    telemetry[56] = ((unsigned char *)&ushort)[1];
    telemetry[57] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[58];
    ((unsigned char *)&ushort)[0] = telemetry[59];
    return ushort;
}
void EPSTelemetryContainer::setPanelYmCurrent(short ushort)
{
    telemetry[58] = ((unsigned char *)&ushort)[1];
    telemetry[59] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[60];
    ((unsigned char *)&ushort)[0] = telemetry[61];
    return ushort;
}
void EPSTelemetryContainer::setPanelXpCurrent(short ushort)
{
    telemetry[60] = ((unsigned char *)&ushort)[1];
    telemetry[61] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[62];
    ((unsigned char *)&ushort)[0] = telemetry[63];
    return ushort;
}
void EPSTelemetryContainer::setPanelXmCurrent(short ushort)
{
    telemetry[62] = ((unsigned char *)&ushort)[1];
    telemetry[63] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[64];
    ((unsigned char *)&ushort)[0] = telemetry[65];
    return ushort;
}
void EPSTelemetryContainer::setPanelYpVoltage(short ushort)
{
    telemetry[64] = ((unsigned char *)&ushort)[1];
    telemetry[65] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[66];
    ((unsigned char *)&ushort)[0] = telemetry[67];
    return ushort;
}
void EPSTelemetryContainer::setPanelYmVoltage(short ushort)
{
    telemetry[66] = ((unsigned char *)&ushort)[1];
    telemetry[67] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[68];
    ((unsigned char *)&ushort)[0] = telemetry[69];
    return ushort;
}
void EPSTelemetryContainer::setPanelXpVoltage(short ushort)
{
    telemetry[68] = ((unsigned char *)&ushort)[1];
    telemetry[69] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[70];
    ((unsigned char *)&ushort)[0] = telemetry[71];
    return ushort;
}
void EPSTelemetryContainer::setPanelXmVoltage(short ushort)
{
    telemetry[70] = ((unsigned char *)&ushort)[1];
    telemetry[71] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYpTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[72];
    ((unsigned char *)&ushort)[0] = telemetry[73];
    return ushort;
}
void EPSTelemetryContainer::setPanelYpTemperature(short ushort)
{
    telemetry[72] = ((unsigned char *)&ushort)[1];
    telemetry[73] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelYmTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[74];
    ((unsigned char *)&ushort)[0] = telemetry[75];
    return ushort;
}
void EPSTelemetryContainer::setPanelYmTemperature(short ushort)
{
    telemetry[74] = ((unsigned char *)&ushort)[1];
    telemetry[75] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXpTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[76];
    ((unsigned char *)&ushort)[0] = telemetry[77];
    return ushort;
}
void EPSTelemetryContainer::setPanelXpTemperature(short ushort)
{
    telemetry[76] = ((unsigned char *)&ushort)[1];
    telemetry[77] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getPanelXmTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[78];
    ((unsigned char *)&ushort)[0] = telemetry[79];
    return ushort;
}
void EPSTelemetryContainer::setPanelXmTemperature(short ushort)
{
    telemetry[78] = ((unsigned char *)&ushort)[1];
    telemetry[79] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptYpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[80];
    ((unsigned char *)&ushort)[0] = telemetry[81];
    return ushort;
}
void EPSTelemetryContainer::setMpptYpCurrent(short ushort)
{
    telemetry[80] = ((unsigned char *)&ushort)[1];
    telemetry[81] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptYmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[82];
    ((unsigned char *)&ushort)[0] = telemetry[83];
    return ushort;
}
void EPSTelemetryContainer::setMpptYmCurrent(short ushort)
{
    telemetry[82] = ((unsigned char *)&ushort)[1];
    telemetry[83] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptXpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[84];
    ((unsigned char *)&ushort)[0] = telemetry[85];
    return ushort;
}
void EPSTelemetryContainer::setMpptXpCurrent(short ushort)
{
    telemetry[84] = ((unsigned char *)&ushort)[1];
    telemetry[85] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptXmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[86];
    ((unsigned char *)&ushort)[0] = telemetry[87];
    return ushort;
}
void EPSTelemetryContainer::setMpptXmCurrent(short ushort)
{
    telemetry[86] = ((unsigned char *)&ushort)[1];
    telemetry[87] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptYpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[88];
    ((unsigned char *)&ushort)[0] = telemetry[89];
    return ushort;
}
void EPSTelemetryContainer::setMpptYpVoltage(short ushort)
{
    telemetry[88] = ((unsigned char *)&ushort)[1];
    telemetry[89] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptYmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[90];
    ((unsigned char *)&ushort)[0] = telemetry[91];
    return ushort;
}
void EPSTelemetryContainer::setMpptYmVoltage(short ushort)
{
    telemetry[90] = ((unsigned char *)&ushort)[1];
    telemetry[91] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptXpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[92];
    ((unsigned char *)&ushort)[0] = telemetry[93];
    return ushort;
}
void EPSTelemetryContainer::setMpptXpVoltage(short ushort)
{
    telemetry[92] = ((unsigned char *)&ushort)[1];
    telemetry[93] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getMpptXmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[94];
    ((unsigned char *)&ushort)[0] = telemetry[95];
    return ushort;
}
void EPSTelemetryContainer::setMpptXmVoltage(short ushort)
{
    telemetry[94] = ((unsigned char *)&ushort)[1];
    telemetry[95] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellYpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[96];
    ((unsigned char *)&ushort)[0] = telemetry[97];
    return ushort;
}
void EPSTelemetryContainer::setCellYpCurrent(short ushort)
{
    telemetry[96] = ((unsigned char *)&ushort)[1];
    telemetry[97] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellYmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[98];
    ((unsigned char *)&ushort)[0] = telemetry[99];
    return ushort;
}
void EPSTelemetryContainer::setCellYmCurrent(short ushort)
{
    telemetry[98] = ((unsigned char *)&ushort)[1];
    telemetry[99] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellXpCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[100];
    ((unsigned char *)&ushort)[0] = telemetry[101];
    return ushort;
}
void EPSTelemetryContainer::setCellXpCurrent(short ushort)
{
    telemetry[100] = ((unsigned char *)&ushort)[1];
    telemetry[101] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellXmCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[102];
    ((unsigned char *)&ushort)[0] = telemetry[103];
    return ushort;
}
void EPSTelemetryContainer::setCellXmCurrent(short ushort)
{
    telemetry[102] = ((unsigned char *)&ushort)[1];
    telemetry[103] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellYpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[104];
    ((unsigned char *)&ushort)[0] = telemetry[105];
    return ushort;
}
void EPSTelemetryContainer::setCellYpVoltage(short ushort)
{
    telemetry[104] = ((unsigned char *)&ushort)[1];
    telemetry[105] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellYmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[106];
    ((unsigned char *)&ushort)[0] = telemetry[107];
    return ushort;
}
void EPSTelemetryContainer::setCellYmVoltage(short ushort)
{
    telemetry[106] = ((unsigned char *)&ushort)[1];
    telemetry[107] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellXpVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[108];
    ((unsigned char *)&ushort)[0] = telemetry[109];
    return ushort;
}
void EPSTelemetryContainer::setCellXpVoltage(short ushort)
{
    telemetry[108] = ((unsigned char *)&ushort)[1];
    telemetry[109] = ((unsigned char *)&ushort)[0];
}
short EPSTelemetryContainer::getCellXmVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[110];
    ((unsigned char *)&ushort)[0] = telemetry[111];
    return ushort;
}
void EPSTelemetryContainer::setCellXmVoltage(short ushort)
{
    telemetry[110] = ((unsigned char *)&ushort)[1];
    telemetry[111] = ((unsigned char *)&ushort)[0];
}
